# Generated by Django 3.2.3 on 2021-12-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='initial_price',
        ),
        migrations.AddField(
            model_name='item',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='urls',
            field=models.TextField(),
        ),
    ]
