# Generated by Django 3.2.3 on 2021-12-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_item_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
