# Generated by Django 3.2.3 on 2021-12-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_item_last_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_site',
            field=models.CharField(default='', max_length=200),
        ),
    ]
