# Generated by Django 3.2.3 on 2021-12-09 21:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_item_last_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=8), max_digits=8),
        ),
    ]
