# Generated by Django 3.2.3 on 2021-12-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20211209_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='initial_price',
        ),
        migrations.AddField(
            model_name='item',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=8), max_digits=8),
        ),
    ]
