# Generated by Django 3.2.3 on 2021-12-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20211209_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
