# Generated by Django 3.2.3 on 2021-12-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20211209_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default_item.jpg', upload_to='item_pics'),
        ),
    ]
