# Generated by Django 3.2.3 on 2021-12-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='item_pics'),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_site',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
